### ISSUE TITLE
JsonIgnore does not work as expected

### ISSUE THREAD

**Issue by keremulutas** [json-iterator/java#71]
Hello, first of all, thanks for this great library. Here is my problem:

I have a class with some fields to be bound from incoming JSON data, and a field which has an interface type and calculated from one of the fields (decoded from ProtoBuf payload to be specific)

```
public class Test {
    @JsonProperty("id") private String id;
    @JsonProperty("payload") private String payload;

    // Message is interface of type com.google.protobuf.Message
    @JsonIgnore Message message;
}
```

When I try to deserialize like this:

`Test t = JsonIterator.deserialize(source_str, Test.class);`

I get this exception:

```
com.jsoniter.spi.JsonException: com.jsoniter.spi.JsonException: com.jsoniter.spi.JsonException: no constructor for: interface com.google.protobuf.Message
	at com.jsoniter.ReflectionObjectDecoder.<init>(ReflectionObjectDecoder.java:29) ~[jsoniter-0.9.12.jar:?]
	at com.jsoniter.ReflectionDecoderFactory.create(ReflectionDecoderFactory.java:23) ~[jsoniter-0.9.12.jar:?]
	at com.jsoniter.Codegen.gen(Codegen.java:70) ~[jsoniter-0.9.12.jar:?]
	at com.jsoniter.Codegen.getDecoder(Codegen.java:35) ~[jsoniter-0.9.12.jar:?]
	at com.jsoniter.JsonIterator.read(JsonIterator.java:336) ~[jsoniter-0.9.12.jar:?]
	at com.jsoniter.JsonIterator.deserialize(JsonIterator.java:381) ~[jsoniter-0.9.12.jar:?]
	at com.jsoniter.JsonIterator.deserialize(JsonIterator.java:369) ~[jsoniter-0.9.12.jar:?]
	... 6 more
```

I'm using Reflection decoder - I didn't explicitly set any other decoders.

What can I do about this? Is this a bug or is there something I'm missing?

**Comment by taowen** [comment]
`JsoniterAnnotationSupport.enable` for your current version

In the coming version, this will not be necessary

**Comment by keremulutas** [comment]
I've already done that, sorry - forgot to mention.

I'm on a multithread environment, so suspected I should run `JsoniterAnnotationSupport.enable();` on every thread - I tried that and the result is the same.

**Comment by taowen** [comment]
can you try a newer version? https://oss.sonatype.org/content/repositories/snapshots/com/jsoniter/jsoniter/0.9.13-SNAPSHOT/

**Comment by keremulutas** [comment]
Same exception again. Here is the stacktrace:

```
Exception in thread "main" com.jsoniter.spi.JsonException: com.jsoniter.spi.JsonException: no constructor for: interface com.google.protobuf.Message
	at com.jsoniter.ReflectionObjectDecoder.<init>(ReflectionObjectDecoder.java:31)
	at com.jsoniter.ReflectionDecoderFactory.create(ReflectionDecoderFactory.java:26)
	at com.jsoniter.Codegen.gen(Codegen.java:54)
	at com.jsoniter.Codegen.getDecoder(Codegen.java:24)
	at com.jsoniter.JsonIterator.read(JsonIterator.java:355)
	at com.jsoniter.JsonIterator.read(JsonIterator.java:344)
	at com.jsoniter.JsonIterator.deserialize(JsonIterator.java:411)
	at com.jsoniter.JsonIterator.deserialize(JsonIterator.java:381)
	at Main.main(Main.java:55)
Caused by: com.jsoniter.spi.JsonException: no constructor for: interface com.google.protobuf.Message
	at com.jsoniter.ReflectionObjectDecoder.init(ReflectionObjectDecoder.java:43)
	at com.jsoniter.ReflectionObjectDecoder.<init>(ReflectionObjectDecoder.java:29)
	... 8 more
```

**Comment by taowen** [comment]
should be fixed in the latest snapshot version now

**Comment by keremulutas** [comment]
Made sure I used latest snapshot version (........../.m2/repository/com/jsoniter/jsoniter/0.9.13-SNAPSHOT/jsoniter-0.9.13-20170616.083306-4.jar) - the problem still exists.

**Comment by taowen** [comment]
@keremulutas If you are using the latest version, `JsoniterAnnotationSupport` class is gone.  And ReflectionObjectDecoder will have 

```
    private void addBinding(ClassInfo classInfo, final Binding binding) {
        if (binding.fromNames.length == 0) {
            return;
        }
```

**Comment by keremulutas** [comment]
I noticed a bug on my side and verified it is working as expected now.

Sorry about the inconvenience and thanks! Keep up the good work!
